### ISSUE TITLE
Install fails due to mixed use of smbus and smbus2

### ISSUE THREAD

**Issue by sreknob** [geeekpi/upsplus#2]
```bash
pi@luke-pi:~/Documents/upsplus $ sudo ./install.sh
[info] Welcome to 52Pi Technology UPS Plus auto-install Program!.
[info] More information please visit here:.
[info] -----------------------------------------------------.
[info] https://wiki.52pi.com/index.php/UPS_Plus_SKU:_EP-0136.
[info] -----------------------------------------------------.
[info] Start the configuration environment check....
[ ok ] Network status is ok....
[info] Start the software check....
[ ok ] git has been installed..
[ ok ] pi-ina219 library has been installed.
[ ok ] smbus2 library has been installed.
[info] create /root/bin directory....
[info] Create python3 script in location: /root/bin/upsPlus.py Successful.
[ ok ] Create UPS Plus IoT customer service python script successful.
[info] Create crontab list for pi user..
* * * * * /usr/bin/python3 /root/bin/upsPlus.py
* * * * * /usr/bin/python3 /root/bin/upsPlus_iot.py
[info] crontab has been created successful!.
------------------------------------------------------------
------Current information of the detected Raspberry Pi------
------------------------------------------------------------
Raspberry Pi Supply Voltage: 5.256 V
Raspberry Pi Current Current Consumption: 1759.966 V
Raspberry Pi Current Power Consumption: 1586.207 V
------------------------------------------------------------
-------------------Batteries information-------------------
------------------------------------------------------------
Voltage of Batteries: 4.176 V
Battery Current (discharge) Rate: 26.098 mA
Current Battery Power Consumption: 14.634 mW
------------------------------------------------------------
Traceback (most recent call last):
  File "/root/bin/upsPlus.py", line 57, in <module>
    aReceiveBuf.append(bus.read_byte_data(DEVICE_ADDR, i))
  File "/usr/local/lib/python3.7/dist-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
[FAIL] UPS Plus Installation is Incomplete! ... failed!
[info] Please visit wiki for more information:.
[info] -----------------------------------------------------.
[info] https://wiki.52pi.com/index.php/UPS_Plus_SKU:_EP-0136.
[info] -----------------------------------------------------.
```
See PR #1 which properly references smbus2 in the repo rather than smbus.

**Comment by nickfox-taterli** [comment]
Thank you for the patch.
