### ISSUE TITLE
UPS not responding after update

### ISSUE THREAD

**Issue by gabrielbergeron** [geeekpi/upsplus#66]
I was using the ups for a long time on the version 3 and then decided to update since I saw on the github there was a newer version.

While upgrading everything went great I had a successfull message at the end and then the UPS powered off by itself.
After that, the pi would want to turn on anymore. I see the red light on the ups on and one bluelight slowly flashing (I don't have the batteries pluged in at this point).

I tried to reflash the firmware by powering the pi and the ups seperatly, but the pi cannot communicate with the ups I get a I/O error.
```
Traceback (most recent call last):
  File "OTA_firmware_upgrade.py", line 51, in <module>
    bus.write_byte_data(0x18, i + 1, data[i])
  File "/home/pi/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 455, in write_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
```
```
Traceback (most recent call last):
  File "upsplus_iot.py", line 36, in <module>
    aReceiveBuf.append(bus.read_byte_data(DEVICE_ADDR, i))
  File "/home/pi/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
```

I used a voltmeter and checked the voltage between the pins that connect the raspberry pi and the ups and I get only 3V.
Any one have an Idea what I can do with that? it's a quite deceiving experience.

**Comment by gabrielbergeron** [comment]
Sorry about the post, I finally figured out... It was a series of coincidences.

- First, I didn't know that the first time you power it after the update, it doesn't want to power up on batteries only, I guess it's because it doesnt know the voltage yet.
- Second, my nuts that held the raspberry pi were loose so the connection wasn't correctly given to the pins.

After securing the nut and re-plugging the usb-c power supply it works and I'm able to communicate with the ups again.
